global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'uno1victor@gmail.com'
  smtp_auth_username: 'uno1victor@gmail.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  receiver: firing-only
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  routes:
    - match:
        severity: critical
      receiver: email-slack
      continue: true

    - match:
        severity: warning
      receiver: firing-only

receivers:
  - name: firing-only

  - name: email-slack
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#botalerts'
        send_resolved: true
        username: 'AlertmanagerBot'
    email_configs:
      - to: 'uno1victor@hotmail.com'
        send_resolved: true
        from: 'uno1victor@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'uno1victor@gmail.com'
        auth_password: '${SMTP_PASSWORD}'
        require_tls: true

