apiVersion: 1

contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: email-recipient
        type: email
        settings:
          addresses: uno1victor@gmail.com
      - uid: slack-recipient
        type: slack
        settings:
          recipient: '#botalerts'
          url: ${SLACK_WEBHOOK_URL}
          username: 'GrafanaBot'

  - orgId: 1
    name: GrafanaOnly
    receivers: []

  - orgId: 1
    name: grafana-default
    receivers: []

