apiVersion: 1

receiver: grafana-default-email
group_by:
  - alertname
group_wait: 10s
group_interval: 5m
repeat_interval: 1h

routes:
  - receiver: EmailSlackAlertas
    matchers: 'severity="critical"'

  - receiver: GrafanaOnly
    matchers: 'severity="warning"'

