{
 "title": "Métricas HTTP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "P90 Duración HTTP (método/ruta/status)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, method, path, status))"
    }
   ]
  },
  {
   "title": "P95 Duración HTTP (método/ruta)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, method, path))"
    }
   ]
  },
  {
   "title": "Promedio duración HTTP (método/ruta)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(demo_api_request_duration_seconds_sum[5m])) by (method, path) / sum(rate(demo_api_request_duration_seconds_count[5m])) by (method, path)"
    }
   ]
  }
 ]
}